COMP: Issue warning for invalid historical code
There is an outstanding issue with computing spacing for objects.
It appears that the previous code was incorrectly using invalid
values for computing volumetric values from spatial objects.

The code currently appears to work, and generates warnings for
computations of spacing that were likely incorrect previously (See note by Stephen Aylward below).

SpatialObjects do not have Get/SetSpacing member functions for all objects
any longer.  std::cerr << "WARNING:  spacing measurements disabled in for spatial objects in ITKv5" << std::endl;
//HACK TODO Need to figure out what to do about spacing in ITK v5  Asking Stephen Aylward for advice

I need some help from someone who better understands the purpose of this code to address the final spatial object conern.

From: Stephen Aylward <stephen.aylward@kitware.com>
Date: Thursday, February 17, 2022 at 4:12 PM
To: Johnson, Hans J <hans-johnson@uiowa.edu>
Subject: [External] Re: Spatial Object code updates from ITKv4
Hi,

Spatial objects are now only encoded using physical space.  There is no concept of spacing, since there is no need to translate from index space to physical space.

When an old spatial object is read, it will be converted into physical space.   When it is saved, it will remain in physical space.

New objects are created and saved in physical space.

Hope that helps.  Note there are two other related concepts: object space (the native coordinate system of the object) and world space (the coordinate system of the object after it has been transformed by the hierarchy of transforms defined by its parent-child relationships).  I hope the software guide details on this are clear.  If I need to update them, please let me know.

Thanks for asking!!
Stephen

On Thu, Feb 17, 2022 at 12:01 PM Johnson, Hans J <hans-johnson@uiowa.edu> wrote:
Stephen,

I am trying to update some old DTI processing code from ITKv4 to ITKv5 in order to resurrect some old data analysis processing.

I am struggling to identify how to get the spacing information from a spatial object:

https://github.com/NIRALUser/DTIProcessToolkit/blob/master/Applications/fiberstats.cxx#L46

/Users/johnsonhj/src/DTIProcessToolkit/Applications/fiberstats.cxx:46:34: error: no member named 'GetSpacing' in 'itk::GroupSpatialObject<3>'
  const double* spacing = group->GetSpacing();
                          ~~~~~  ^

Any suggestions would be welcome.

Hans